mpusz/mp-units

doc/INSTALL.md

The previous remote URL did not work, so use the URL specified on the Bintray website.
* doc/INSTALL.md: Fix conan-mpusz remote URL

Fix conan-mpusz remote URL

---

src/include/units/quantity.h
test/unit_test/test_quantity.cpp

- The standard cast no longer changes the representation type.
- One can change the unit type without changing the representation type.
- One can change the representation type without changing the unit type.

Made quantity_cast more versatile

---

src/include/units/quantity.h

- Divisions are now made at compile time.
- Only runtime multiplications are left.

Optimized floating point unit conversions

---

doc/DESIGN.md

I believe that zero "exponents are elided" rule concerns exponent not base-dimension, so have modified parts where I think exponent rather than base dimension should apply

DESIGN.md :  clarification of exponents v base-dimensions

---

src/include/units/bits/base_units_ratio.h
src/include/units/bits/unit_text.h
src/include/units/physical/si/prefixes.h
src/include/units/prefix.h
src/include/units/quantity.h
src/include/units/quantity_cast.h
src/include/units/ratio.h
test/unit_test/runtime/fmt_test.cpp
test/unit_test/static/quantity_test.cpp
test/unit_test/static/ratio_test.cpp
test/unit_test/static/si_test.cpp
test/unit_test/static/unit_test.cpp

https://github.com/mpusz/units/issues/14
This "works", as in it passes all static and runtime tests.
However quite a few of the tests have been "modified" to make them pass. Whether
this is legitimate is debatable and should be the source of some thought /
discussion.
1. many of the static tests and some of the runtime tests have had the input
ratios of the tests modified in the following way. eg ratio<3,1000> =>
ratio<3,1,-3>. ie they have been "canonicalised".
There are obviously an infinite number of ratios which represent the same
rational number. The way `ratio` is implemented it always moves as "many powers
of 10" from the `num` and `den` into the `exp` and that makes the `canonical`
ratio.
Because these are all "types" and the lib uses is_same all over the place, only
exact matches …

implementing ratio<num,den,exp> which replaces ratio<num,den>

---

src/include/units/bits/ratio_maths.h
src/include/units/quantity.h
src/include/units/ratio.h
test/unit_test/runtime/fmt_units_test.cpp
test/unit_test/static/ratio_test.cpp

really finds the maximum common ration as opposed to previous algo which
simplified on the exp part of the ratio by using std::min
most of new code credit to Conor Williams
discussion and additional doc here:
https://github.com/mpusz/units/issues/62#issuecomment-588152833
test case was 1yd + 1in = 37in => added as a test
commenting out unusued ratio_add and its tests
if to be reintroduced, should also use the new gcd routines
additonal change was required to check in `safe_divisible` concept
den=1 is not sufficient anymore. reusing new gcd routines
moved ratio nomalize and new gcd routines into new, separate bits/ratio_maths.h
this resolves #62

employing more mathemtaically correct ratio_gcd calc (for common ratio)

---

doc/DESIGN.md
src/include/units/bits/external/text_tools.h
src/include/units/concepts.h
test/unit_test/runtime/fmt_units_test.cpp

this improves the situation for #55 (doesn't solve it outright)
motivating examples which now work are:
1q_mi * 1q_mi * 1q_mi
1q_au * 1q_au
tests added and docs updated

extending the range of operator* for incoherent units with large num/den

---

src/include/units/format.h

This should solve #76 by propagating all the types described in the ["standard format specifier" section](http://eel.is/c++draft/format.string.std) found when parsing a quantity to the representation of the of the underlying `Rep`

Added types in formatting

---

src/include/units/format.h
test/unit_test/runtime/fmt_test.cpp

I've done some modifications:
- removed `p` , `s` and `c` formatting types, since they're valid only for pointers, strings and chars respectively
- added the `#` specifier to print base prefixes
- added unit tests for the formatting types introduced in #79 
Do you think something is still missing?

Add types in formatting - updates and tests

---

src/include/units/format.h
test/unit_test/runtime/fmt_test.cpp

I've implemented the new grammar, as requested in #81 .
Talking about the `A` unit modifier from #78 , it's already in the list of the currently valid unit modifiers, but using it will result in an exception ("unit modifier 'A' is not implemented"). When the code for the modifier will be ready, we will have to remove exception (line 240) and change the code in the `units_formatter::on_quantity_unit` member function (line 236).
What do you think about it?

New formatting grammar implemented

---

src/include/units/format.h

In this PR I made these small changes:
- simplified a bit the code merging the `ascii_only` functionality in the `unit_specs` one
- made some names more explanatory regarding their use
- added a small guide that could help if some new functionality needs to be added in the future. It may contains language errors (English is not my native language)
This is a minor PR, but I hope it can make the code more accessible for further extensions.
What do you think about it?

Minor changes in format.h

---

src/include/units/math.h
test/unit_test/runtime/math_test.cpp

Maybe the epsilon (and any other functions to be added to mimic std::numeric_limits) should relate to the "quantity_values" class.

Added absolute functions (abs, fabs) and epsilon to math.h, and tests

---

src/include/units/physical/si/absorbed_dose.h
src/include/units/physical/si/area.h
src/include/units/physical/si/capacitance.h
src/include/units/physical/si/catalytic_activity.h
src/include/units/physical/si/conductance.h
src/include/units/physical/si/current.h
src/include/units/physical/si/energy.h
src/include/units/physical/si/force.h
src/include/units/physical/si/frequency.h
src/include/units/physical/si/inductance.h
src/include/units/physical/si/length.h
src/include/units/physical/si/luminous_intensity.h
src/include/units/physical/si/magnetic_flux.h
src/include/units/physical/si/magnetic_induction.h
src/include/units/physical/si/mass.h
src/include/units/physical/si/power.h
src/include/units/physical/si/pressure.h
src/include/units/physical/si/resistance.h
src/include/units/physical/si/time.h
src/include/units/physical/si/voltage.h
src/include/units/physical/si/volume.h
src/include/units/unit.h
test/unit_test/runtime/fmt_test.cpp
test/unit_test/static/si_test.cpp

Dear Mr. Mateusz Pusz,
I added more prefixed SI units after I found that ```nanometer``` was missing. I needed that unit for my SPICE circuit simulation work. Please let me know if there is anything I am missing - if I added anything redundant, conflicting, etc ...
Most importantly, I added ```alias_unit``` and ```prefixed_alias_unit``` types to deal with units such as ```litre``` which, due to having been equivalent to ```cubic_decimetre```, used to have its unit printed out as ```dm³``` rather than ```l```. ```tonne```, on the other hand, due to having been a ```scaled_unit``` from kilogram, had its unit printed out properly as ```t```. However, after having defined ```megagram```, which is equivalent to ```tonne```, I would get an error concerning a redeclaration of ```friend auto …
```

alias_unit

---

src/include/units/physical/si/angle.h

si angle header : fix wrong literal return type so now returns an angle not a length

si angle header : angle literal should return an angle not a length

---

example/CMakeLists.txt
example/foot_pound_second.cpp
src/include/units/physical/fps/acceleration.h
src/include/units/physical/fps/area.h
src/include/units/physical/fps/density.h
src/include/units/physical/fps/energy.h
src/include/units/physical/fps/force.h
src/include/units/physical/fps/length.h
src/include/units/physical/fps/mass.h
src/include/units/physical/fps/power.h
src/include/units/physical/fps/pressure.h
src/include/units/physical/fps/speed.h
src/include/units/physical/fps/time.h
src/include/units/physical/fps/volume.h
src/include/units/unit.h
test/unit_test/static/CMakeLists.txt
test/unit_test/static/fps_test.cpp
test/unit_test/static/si_fps_test.cpp

Created the foot-pound-second system, based on the setup of the CGS system.
Involved some messing about with units.h to help with symbols:
1) 'noble_deduced_units' - same as deduced units but can create children (placeholder name, the idea is that they can pass on their titles)
2) 'named_deduced_derived_units' - deduced units that have a supplied symbol, used to deduce the ratio for nautical miles per hour but set the symbol to 'knot' instead of 'mi(naut) / h'
SI tonnes are used in the example, but are displayed as Mg so don't seem to pick up the symbol 't'.

Foot pound second system

---

src/include/units/physical/si/substance.h

corrected copy-paste error in mole definition

---

src/include/units/quantity.h

Discarding these values is a signal that you should be using the prefix operator.

feat: nodiscard for postfix increment and decrement

---

src/include/units/bits/external/fixed_string.h
src/include/units/symbol_text.h

From GCC11:
```
_deps/mp-units-src/src/include/units/bits/external/fixed_string.h: In instantiation of ‘constexpr units::basic_fixed_string<CharT, N>::basic_fixed_string(const CharT (&)[(N + 1)]) [with CharT = char; long unsigned int N = 0]’:
_deps/mp-units-src/src/include/units/bits/external/text_tools.h:32:58:   required from here
<src>/build/_deps/mp-units-src/src/include/units/bits/external/fixed_string.h:47: warning: comparison of unsigned expression in ‘< 0’ is always false [-Wtype-limits]
47 |     for (std::size_t i = 0; i < N; ++i) data_[i] = txt[i];
|                             ~~^~~
```
Caused by:
```C++
template<std::intmax_t Value>
requires (0 <= Value) && (Value < 10)
inline constexpr basic_fixed_string superscript_number = "";
```

refactor: avoid always false comparison

---

src/include/units/bits/external/hacks.h

It was removed from the wrong header: https://github.com/mpusz/units/commit/51b6d2f974ef2ab081d229a1f8e5484247195963#diff-caa17227b73152074e21c79360e64abf.

refactor: remove Expects macro

---

src/include/units/bits/pow.h
src/include/units/pow.h
src/include/units/prefix.h
src/include/units/quantity.h
src/include/units/quantity_cast.h

All that's left is `format.h`, which results in an ICE. I'll report that to the developers. `quantity_cast.h` and `quantity.h` have a mutual dependency, which is ["exciting"](https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=6bdbf0f37bda2587a4e82cbb956de7a159a397ae).

feat: enable GCC modules compilation of header units

---

src/include/units/bits/external/type_traits.h
src/include/units/concepts.h
src/include/units/physical/dimensions.h
src/include/units/quantity_cast.h

Where appropriate, use specialization instead of instantiation. See also https://wg21.link/P2098.

refactor: *_instantation_of to *_specialization_of

---

src/include/units/concepts.h

With VS 2019 16.8, it could have been
```C++
template<Dimension D>
using dimension_unit = decltype([]{
if constexpr (BaseDimension<D>)
return TYPENAME D::base_unit{};
else
return TYPENAME D::coherent_unit{};
}());
```

refactor: simplify dimension_unit

---

src/include/units/physical/dimensions.h

Continuation of johelegp@22e6107.
What do you think we should do in this case?
```
hello_units.cpp: In function ‘int main()’:
hello_units.cpp:40:57: error: no matching function for call to ‘quantity_cast<units::physical::si::metre_per_second>(units::quantity<units::unknown_dimension<units::exp<units::physical::si::dim_length, 1, 1>, units::exp<units::physical::si::dim_time, -1, 1> >, units::scaled_unit<units::ratio{1397, 3125, 0}, units::unknown_coherent_unit>, double>&)’
40 |   Speed AUTO v3 = quantity_cast<si::metre_per_second>(v2);
```
I'm still wrapping my head about things, so I can't make an immediate call. What should the behavior be here? What should the type of `v3` be?

feat: Downcasting with UNITS_DOWNCAST OFF

---

docs/framework/text_output.rst
src/include/units/format.h
test/unit_test/runtime/fmt_test.cpp

These changes allows to enable localization via the `'L'` _units-rep-modifier_ in format strings like `"{:%LQ %q}"`, as requested in #34.1.
Do you think something is missing?

Feat: minimal support for localization

---

src/include/units/physical/si/time.h

I was playing around with custom temporal "rate" units, and noticed that the following code:
```cpp
Time auto all_day_long = 1_q_d;
fmt::print("hours = {}\n", quantity_cast<si::hour>(all_day_long));
fmt::print("days  = {}\n", quantity_cast<si::day>(all_day_long));
```
produced the following output:
```
hours = 24 h
days  = 1 h
```
This led me to discover a typo in the definition of the `day` unit.
Thanks for the great work on the library!

fix: Output formatted in days has right scaling but wrong unit symbol (`h` instead of `d`)

---

src/include/units/bits/ratio_maths.h
src/include/units/ratio.h
src/include/units/symbol_text.h

This removes a warning:
```
_deps/microsoft.gsl-src/include/gsl/gsl_assert:2:97: note: ‘#pragma message: This header will soon be removed. Use <gsl/assert> instead of <gsl/gsl_assert>’
2 | #pragma message("This header will soon be removed. Use <gsl/assert> instead of <gsl/gsl_assert>")
|                                                                                                 ^
```

refactor: <gsl/gsl_assert> to <gsl/assert>

---

src/include/units/bits/ratio_maths.h
src/include/units/ratio.h
src/include/units/symbol_text.h

Reverts mpusz/units#181
The next version of GSL will have the headers with redundant `gsl_` in their names deprecated.
IIRC, you don't mind not using the `revert:` conventional commit.

Revert "refactor: <gsl/gsl_assert> to <gsl/assert>"

---

src/include/units/bits/constexpr_math.h
src/include/units/bits/dimension_op.h
src/include/units/bits/math_concepts.h
src/include/units/bits/pow.h
src/include/units/bits/root.h
src/include/units/math.h
src/include/units/ratio.h
test/unit_test/runtime/math_test.cpp
test/unit_test/static/math_test.cpp
test/unit_test/static/ratio_test.cpp

Added support for `pow<N, D>(Quantity)` and `pow<N, D>(ratio)` based on existing `sqrt` behaviour. This generalizes `sqrt` for any rational powers.
- Added compile-time versions of `log`, `exp` and `pow` based on finite sums, no binary tricks. `log` precision is about 1E-16 relative error compared to `std::log`, while `exp` and `pow`, as used in root-finding, are about 1E-14 which is more than enough for integer roots.
- Generalized `make_exp_even` to `make_exp_align` for any positive integer
- Improved `pow` by using [exponentation by squaring](https://en.wikipedia.org/wiki/Exponentiation_by_squaring) instead of recursive template multiplications
- General root function for integers with faster runtime path, unit tests for both paths to make sure equivalent results and correct truncation …

Support rational powers

---

cmake/warnings.cmake
src/include/units/quantity.h
test/unit_test/static/CMakeLists.txt

fix: restore user-warnings within the library implementation

---

docs/CHANGELOG.md
src/include/units/bits/external/downcasting.h

Fixes a point mentioned in https://github.com/mpusz/units/issues/199#issue-777819614.

fix: downcasting facility for non-default-constructible types

---

example/alternative_namespaces/timer.h

On my machine, the CTest CMake target fails with `-Werror=sign-compare` without that fix. The reason is [`std::difftime`](https://en.cppreference.com/w/cpp/chrono/c/difftime) operates on `std::time_t`, while the rest of that example uses `std::clock_t`. These two types are not related in semantics as far as I can tell. However [`std::clock_t`](https://en.cppreference.com/w/cpp/chrono/c/clock_t) is specified as an "arithmetic type", so simply subtracting should be ok. Furthermore, the corresponding [C `clock_t` example](https://en.cppreference.com/w/c/chrono/clock_t) explicitly highlights subtraction and conversion to double.

fixed -Wsign-conversion warning in doubtful conversion between std::clock_t and std::time_t

---

src/include/units/data/base/information.h
src/include/units/data/derived/bitrate.h
test/unit_test/runtime/digital_info_test.cpp
test/unit_test/static/data_test.cpp

This PR add a si prefix based bit unit. This is often used in low level calculations of bit rates in conjunction with symbol rates or frequencies. (e.g. 1000Mb Ethernet, 10Gbit optical link)
Closes #186.

Add SI prefix to bit unit

---

src/include/units/data/data.h
src/include/units/data/derived/symbolrate.h
test/unit_test/runtime/digital_info_test.cpp

Add the symbolrate as alias for frequency with unit baud. This unit is commonly used in information systems as way to express the amount of symbols transfer per second. A symbol can encode several bits and the symbolrate multiplied by bit will give the bit rate. This pull request has to be seen in conjunction with #188 due to the fact that the symbol rate has a decimal prefix and thus the bitrate as well.
Closes #186.

Add symbolrate as alias unit for frequency

---

src/systems/isq-iec80000/include/units/isq/iec80000/storage_capacity.h

Otherwise the namespace si is not defined

fix: Add missing include

---

src/systems/si/include/units/isq/si/constants.h

substance -> amount_of_substance
temperature -> thermodynamic_temperature

fix: corrected old names in si::constants

---

README.md
docs/quick_start.rst

While testing I found some very minor missing/required (?) defines. It's not much and seasoned units users might easily miss this but I reckoned that other new users of your library might stumble across it as well. Feel free to merge, modify, or close.
The compiler explorer examples seem to miss the following
```
#define UNITS_REFERENCES
#define UNITS_LITERALS
```
defines to execute and recompile slightly modified versions.
Haven't changed anything else other than the updated compiler-explorer links.

adding missing/required (?) '#defines' for compiler-explorer examples

---

src/core/include/units/bits/basic_concepts.h
src/core/include/units/quantity.h
test/unit_test/static/quantity_test.cpp

This PR allows to inherit from the `quantity` template class definition and to provide additional NTTP-type annotations and/or change the signature of the derived class (e.g. ordering of parameter types). For details see also #271
N.B. inheritance is preferred to composition/delegate class to avoid duplication of and also inherent the various required operators ('+','-',..., '+=', ...) 
Up for comments, improvements, and/or suggestions. Thanks again for this great library. :+1:

extended is_quantity<T> to support quantity-derived classes

---

src/core/include/units/quantity.h

As discussed at https://github.com/mpusz/units/commit/80abffc0582f55643a1d9a6d9c58eefe74d5c9e0#commitcomment-56633803.
I believe at some point I questioned why these where constrained with `!Quantity` rather than `Representation`.
This only fixes it for the linear algebra example; there remain other uses of `!Quantity`.
Unrelatedly, this came up while compiling all the static tests with the glob `*.cpp`:
```C++
/home/johel/Documents/C++/Forks/mpusz/units/test/unit_test/static/si_hep_test.cpp:24:10: fatal error: units/isq/si/hep/area.h: No such file or directory
24 | #include <units/isq/si/hep/area.h>
|          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

fix: constraint recursion in GCC 11 for the linear algebra examples

---

src/core/include/units/math.h
test/unit_test/runtime/math_test.cpp
test/unit_test/static/math_test.cpp

Relates to #307 
Adds feature ceil, following the design of floor.
Current problems: There is one runtime unit tests that fails while the same static test passes. I guess this is caused by `fpow10()` see #311

Feat: Ceil

---

src/core/include/units/math.h
test/unit_test/runtime/math_test.cpp
test/unit_test/static/math_test.cpp

Relates to #307 
Overloads for `floor` and `ceil` for quantitiy types. I will include the overload for `round` in #313

Feat: Overloads for floor and ceil accepting quantities

---

src/core/include/units/math.h
test/unit_test/runtime/math_test.cpp
test/unit_test/static/math_test.cpp

Closes #307 
Implementation for `units::round`.
Currently I am struggling with specifying the `requires` clause. You can find my attempt in https://github.com/hofbi/units/commit/76c0b5a5d8bbe7d9f79c795b06ee396ae87cc74d where the commented part is what breaks the build.
Also in `math.h` line 253 `if (static_cast<int>(res_low.number()) & 1)`, I am not sure if doing the `static_cast` to handle floating points is the best approach.

Feat: Round

---

src/core/include/units/magnitude.h
src/core/include/units/ratio.h
test/unit_test/runtime/CMakeLists.txt
test/unit_test/runtime/magnitude_test.cpp
test/unit_test/static/ratio_test.cpp

This is the beginning of the implementation for #300, laying the first foundations.  This seems like a good point to check in and align on direction before we get too far along.  For general context:
_Things we include here:_
- Concepts for `Magnitude`, and `BasePower` (a Magnitude is made up of a canonicalized parameter pack of BasePowers).
- End user interfaces for making magnitudes:
- `as_magnitude<ratio>()`: the main way to make a Magnitude from a rational number.  This handles the "heavy lifting" of converting to a prime factorization.
- `base_power<T>{ratio}`: we handle irrational bases by introducing a type `T`, with a static `long double` member `value` which must be positive.
- Enhanced `ratio` functionality: addition, negation, and implicit construction.
_Work yet undone:_
- A …

Add vector space representation for magnitudes

---

src/core/include/units/bits/derived_unit.h
test/unit_test/static/fps_test.cpp

Fixes cases such as fps::cubic_yard where the ratio was incorrectly scaled.

Fix derived_ratio calculation

---

src/core/include/units/magnitude.h

I don't think this does anything we want. But GCC did complain (but not Clang) when compiling `magnitude.h` as a module. Apparently, it makes them have internal linkage. That doesn't really help in a header, and just makes it easier to commit an ODR violation.

refactor: drop `static` from `constexpr` globals

---

src/core/include/units/magnitude.h
src/core/include/units/ratio.h
test/unit_test/runtime/magnitude_test.cpp
test/unit_test/static/ratio_test.cpp

We provide two new functions, `numerator(m)` and `denominator(m)`, for a
Magnitude `m`.  They fulfill the following conditions:
1. `numerator(m)` and `denominator(m)` are always integer Magnitudes.
2. If `m` is rational, then `m == numerator(m) / denominator(m)`.
If `m` is _not_ rational, then the numerator and denominator are not
especially meaningful (there is no uniquely defined "leftover irrational
part").  However, we choose a convention that matches how humans would
write a mixed number.  For example, sqrt(27/16) would have a numerator
of 3, denominator of 4, and a "leftover part" of sqrt(3), matching the
"human" way of writing this as [(3 * sqrt(3)) / 4].  This has no use
yet, but it may later be useful in printing the Magnitude of an
anonymous Unit for end users.
To further reduce …

Support seamless interop between `ratio` and rational `Magnitude`

---

src/core/include/units/bits/basic_concepts.h
src/core/include/units/bits/unit_text.h
src/core/include/units/magnitude.h
src/core/include/units/prefix.h
src/systems/isq-iec80000/include/units/isq/iec80000/binary_prefixes.h
src/systems/si/include/units/isq/si/prefixes.h
test/unit_test/runtime/magnitude_test.cpp

The biggest "chunk" was the pretty-printing code (`unit_text`), which piggybacked on `ratio`'s normalization to pull out appropriate powers of 10.  I first created a new utility, `extract_power_of_10`, to reproduce this logic.  Unit tests are included.  Then, I used this to update the `ratio_text` implementation.
After this, I upgraded the `prefix` instances to be based on `Magnitude`.  This was mostly mechanical, although I did take advantage of the opportunity to redefine the binary prefixes to be easier to read.
The four commits in the initial version of this PR are structured for readability; reviewers may find it useful to read them individually.
Fixes #300.

Migrate remaining ratio template parameters to Magnitude

---

example/custom_systems.cpp
src/core/include/units/bits/ratio_maths.h
src/core/include/units/chrono.h
src/core/include/units/magnitude.h
src/core/include/units/ratio.h
src/systems/si-hep/include/units/isq/si/hep/area.h
src/systems/si-hep/include/units/isq/si/hep/mass.h
src/systems/si-hep/include/units/isq/si/hep/momentum.h
src/systems/si-iau/include/units/isq/si/iau/length.h
src/systems/si-international/include/units/isq/si/international/length.h
src/systems/si-typographic/include/units/isq/si/typographic/length.h
src/systems/si/include/units/isq/si/catalytic_activity.h
src/systems/si/include/units/isq/si/energy.h
src/systems/si/include/units/isq/si/mass.h
test/unit_test/runtime/magnitude_test.cpp
test/unit_test/static/quantity_test.cpp
test/unit_test/static/ratio_test.cpp
test/unit_test/static/unit_test.cpp

Now that we have Magnitude, which can handle values far outside the range of `std::intmax_t`, we no longer need `exp`.  This makes `ratio` much simpler and easier to reason about, and removes a considerable amount of special-case logic.
The original commits in this PR are structured to have a single logical purpose each, which reviewers may find helpful.
Fixes #369.

Remove `exp` member from `ratio`

---

src/core/include/units/chrono.h

This should fix clang's complaint.

Explicitly qualify `mag<>` that initializes `mag` member

---

src/core/include/units/quantity.h

A similar fix was applied in 417f84258523d2e5f868cf080b7b837328edd501 for the operator*.
Following discussion in https://github.com/mpusz/units/issues/398, it seems appropriate to apply it for operator/.
Other operators (+, -, %) do not seem to suffer from the same problem.

fix: constraint recursion for gcc11 on operator/

---

.github/workflows/ci-check.yml
.pre-commit-config.yaml
example/include/validated_type.h
src/core/include/units/bits/quantity_of.h
src/core/include/units/quantity_point.h
test/unit_test/static/custom_rep_test_min_expl.cpp
test/unit_test/static/fps_test.cpp
test/unit_test/static/test_tools.h

I saw that clang format 15 was released as pre-commit hook. So with this one I am updating the existing hooks and enable clang format. Running it changed a few files.

Pre-commit autoupdate and enable clang-format

---

.github/workflows/ci-conan.yml

I'm raising this pull request based on the observation that the Conan cache is not working.  For example, during the "Create Conan Package" stage when `conan install` is run Catch2 and Fmt packaged are being built and are not found in the synced cache: https://github.com/mpusz/units/actions/runs/3841122699/jobs/6540977771
Although it might seem logical to assume that by pushing the conan data folder to the cache then eventually all build configuration would end up in it this does not appear to be what is happening.  It looks like the Conan cache is uploaded to `"${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/metadata.json') }}`.  However, I can't see any `metadata.json` in the build tree so this part drops off, resulting in a cache key such as …

Move the cachekey to using build information for identiciation.

---

.pre-commit-config.yaml

A Poetry update broke isort: https://github.com/PyCQA/isort/issues/2077
The bug occurs when building from source, which is what pre-commit does. 
The latest version of isort fixes this issue.

Update isort to work around build from source bug

---

src/core-fmt/CMakeLists.txt
src/core/CMakeLists.txt

Added check for gsl::gsl-lite to avoid find_package if targets already added by add_subdirectory(...) and did the same for fmt::fmt and ranges-v3, with out these changes, impossible to use library if dependencies are also subdirectories, complains about not being able to find package (when it no longer needs to)

Added support for use of units as subdirectory when *dependencies* are *also* subdirectories

---

docs/reference/systems/isq/si/uscs/pressure.rst
docs/reference/systems/isq/si_uscs.rst
src/systems/si-uscs/CMakeLists.txt
src/systems/si-uscs/include/units/isq/si/uscs/pressure.h
src/systems/si-uscs/include/units/isq/si/uscs/uscs.h
test/unit_test/static/us_test.cpp

Inch of Mercury (inHg) is used in aviation weather reports in the US.
Please check if this is integrated at the right place.
I compiled and run static tests successfully.

Add "inch of mercury" pressure unit as US Custom Unit

---

src/systems/si/include/mp-units/systems/si/units.h

MinGW defines `pascal`: https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-headers/include/minwindef.h
Same as the Windows SDK: https://github.com/tpn/winsdk-10/blob/master/Include/10.0.16299.0/shared/minwindef.h#L98
This at least protects the units header from that macro, users could still face the issue, but I don't think `#undef`ing the macro globally should be done in a library header.

Work around Windows macro

---

example/unmanned_aerial_vehicle.cpp

This code fixes "control reaches end of non void function" warning that is an error in our project. It does so by adding assertion that is knowingly false. This assertion is not reachable with the proper code, but would become possible to reach if more values are added to the enum.

Fix "control reaches end of non void function" error.

---

docs/users_guide/framework_basics/basic_concepts.md
src/core/include/mp-units/bits/quantity_concepts.h
src/core/include/mp-units/bits/quantity_point_concepts.h
src/core/include/mp-units/customization_points.h
src/core/include/mp-units/quantity.h
src/core/include/mp-units/quantity_point.h
src/utility/include/mp-units/chrono.h
test/unit_test/static/chrono_test.cpp
test/unit_test/static/quantity_point_test.cpp

- existing customization points converting from an external type refactored
- control over explicit/implicit conversion added
- conversion to the external type added
- `std::chrono` types now implicitly convert in both directions

feat: interoperability with other libraries redesigned

---

cmake/ccache.cmake
cmake/modern_project_structure.cmake
example/CMakeLists.txt
example/glide_computer_lib/CMakeLists.txt
example/kalman_filter/CMakeLists.txt
test/CMakeLists.txt
test/unit_test/runtime/CMakeLists.txt
test/unit_test/static/CMakeLists.txt

Currently, cmake is emitting the following warning:
```
CMake Deprecation Warning at cmake/ccache.cmake:23 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
```
Update the CMake min version to 3.5 to unclutter the build logs and ensure users don't get broken by the deprecation.

Update minimum cmake version to 3.5

---

src/core/include/mp-units/math.h

A small number of `math.h` operations are even well-specified for points in the affine space; I identified `isfinite`, `isinf` and `isnan` so far. We should eventually also support [`midpoint`](https://en.cppreference.com/w/cpp/numeric/midpoint) and [`lerp`](https://en.cppreference.com/w/cpp/numeric/lerp) eventually - both of them are currently missing for bare quantities either. Work for another PR.

added support for quantity_point math

---

test/runtime/CMakeLists.txt
test/runtime/almost_equals.h
test/runtime/truncation_test.cpp

I had some doubts regarding the `number * val(num) / val(den) * val(irr)` computation path in `sudo_cast<Q>`, where I see two potential risks:
1. Potential overflow in the  first multiplication (`* val(num)`)
2. Truncation in the division: It appears that `/ val(den) * val(irr)` may lead to more truncation than necessary (i.e. compared to `* val(irr) / val(den)`), depending on the exact values there.
However, so far, I was unable to find an actual edge case. Risk 1 seems to be mitigated through the use of `std::intmax_t` as the intermediate type of computation,. Risk 2 appears to be mitigated by selecting the other (floating-point) computation path whenever irrational factors are involved.
So instead of a bug report, this is now just a PR containing the additional test-cases I used to …

added more testing of `value_cast` conversion accuracy when using integral types

---

CHANGELOG.md
docs/getting_started/quick_start.md
docs/users_guide/framework_basics/design_overview.md
docs/users_guide/framework_basics/the_affine_space.md
example/kalman_filter/kalman_filter-example_6.cpp
example/kalman_filter/kalman_filter-example_7.cpp
example/kalman_filter/kalman_filter-example_8.cpp
example/spectroscopy_units.cpp
src/core/include/mp-units/bits/sudo_cast.h
src/core/include/mp-units/framework/quantity.h
src/core/include/mp-units/framework/quantity_cast.h
src/core/include/mp-units/framework/quantity_spec.h
src/core/include/mp-units/framework/reference.h
src/core/include/mp-units/framework/reference_concepts.h
src/core/include/mp-units/math.h
src/systems/include/mp-units/systems/si/units.h
src/systems/include/mp-units/systems/usc.h
test/static/quantity_point_test.cpp
test/static/usc_test.cpp

Adds `absolute<Reference>` and `delta<Reference>` modifiers that will influence how:
- multiply syntax works
- limit invalid use cases for quantity and quantity_point.
Here are the main points of this new design:
1. All references/units that do not specify point origin (are not offset units) would be considered `delta` by default. This means that `42 * m` will create a `quantity` and would be the same as calling `42 * delta<m>`. 
2. Multiply syntax is extended to allow quantity_point creation with the `42 * absolute<m>` syntax. This will provide an implicit zeroth point origin.
3. For units that specify a point origin (kelvin, degree_Celsius, and degree_Fahrenheit), the user would always need to specify a modifier. This means that:
- `4 * deg_C` does not compile
- `4 * delta<deg_C>` …

Reference specifiers

---

src/core/include/mp-units/bits/fmt.h
src/core/include/mp-units/format.h

fmtlib [v11.0.0](https://github.com/fmtlib/fmt/releases/tag/11.0.0) released today.

fix: Support fmtlib 11.0.0

---

src/core/include/mp-units/framework/expression_template.h
src/core/include/mp-units/framework/magnitude.h
test/runtime/CMakeLists.txt
test/runtime/quantity_test.cpp
test/static/quantity_test.cpp

Since this will only ever be done at compile time (as guaranteed by
using `consteval`), we can afford to prioritize precision over speed. To
compute an Nth root, we simply do a binary search over representable
floating point numbers, looking for the number whose Nth power most
closely matches the original number.
Fixes #474.  We have included a test case reproducing the original
problem exactly.  All tests use "within 4 ULPs" as the criterion, which
is (I believe) equivalent to the googletest `EXPECT_DOUBLE_EQ`
criterion.

Compute values for rational magnitude powers

---

.github/workflows/ci-conan.yml
.github/workflows/ci-test-package-cmake.yml
test/runtime/almost_equals.h
test/runtime/math_test.cpp

macOS 14 is the only platform that tests on arm64 on GitHub Actions (and is available for public repos). We already test on macOS 14, but so far only with Apple Clang. Apple Clang isn't a widely known compiler in terms of standards compliance, so test with upstream clang should be valuable. In particular, Apply Clang doesn't seem to warn about prevision loss from `long` to `long double`, but upstream clang does. Thus, with this PR, we actually detect the causes of issue #611. #611 is already fixed on master, so the (fast-forward) merge should fix the CI issues that will appear.

Run test on macOS 14 with upstream clang

---

.flake8
.github/generate-job-matrix.py
.github/job_matrix.py
.github/workflows/ci-clang-tidy.yml
.github/workflows/ci-conan.yml
.github/workflows/ci-formatting.yml
.github/workflows/ci-freestanding.yml
.github/workflows/ci-test-package-cmake.yml
.github/workflows/citation.yml
.github/workflows/codeql.yml
.github/workflows/documentation.yml

This PR starts using a [dynamic run matrix](https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/#new-fromjson-method-in-expressions) in the four heavier workflows.
It uses a small python script to generate a subset of all possible combinations. For the two biggest workflows (Conan and CMake), it currently employs the following strategy:
1. Test each compiler/platform with a single configuration:
- C++20
- `std::format` where supported
- contract checking with `gsl-lite`
- Debug build
2. Then, it adds randomly selected combinations until each individual settings value appears in at least two combinations
This currently generates 26 different combinations, out of 261 total acceptable combinations (I added Clang 19 to the test-set).
Hopefully, the python code to …

Faster CI: Sparse run matrix, cancel previous jobs on the same branch

---

src/core/include/mp-units/ext/prime.h
test/static/prime_test.cpp

The prime-testing techniques we will use (Miller-Rabin, Strong Lucas) all make heavy usage of modular arithmetic.  Therefore, we lay those foundations here, adding utilities to perform the basic arithmetic operations robustly.  Getting these foundations right is extremely important for the work that will follow.
Since these are internal-only helper functions, we don't bother checking the preconditions, although we state them clearly in the contract comment for each utility.  After C++26, we could add contracts for these.
Helps #509.

Add helpers for modular arithmetic

---

src/core/include/mp-units/ext/prime.h
test/static/prime_test.cpp

This can mark a number as either "probably prime", or "definitely composite".  The first parameter is the base, and the second is the number to test.
See: https://en.wikipedia.org/wiki/Miller%E2%80%93Rabin_primality_test#Strong_probable_primes
Future PRs will build up the Strong Lucas test which complements this, and then form the Baillie-PSW test by composing the two.
Helps #506.

Add Miller-Rabin probable prime test

---

src/core/include/mp-units/ext/prime.h
test/static/prime_test.cpp

The Strong Lucas test coming in the next PR will already be complicated enough.  It'll be convenient, and less distracting, if we already have functions for certain operations we'll need.
One thing we'll need to do is detect inputs that are perfect squares. Fortunately, this is pretty easy to do robustly and quickly, with Newton's method.  We _don't_ want to use `std::sqrt`, because that takes us into the floating point domain for no good reason, which could give us wrong answers for larger integers.
The other thing we need is Jacobi symbols.  These are a lot more obscure, but thankfully, still resonably straightforward to compute. The Wikipedia page (https://en.wikipedia.org/wiki/Jacobi_symbol) has a good explanation, and in particular, good instructions for computing values.
With these …

Add utilities to make Strong Lucas tests easier

---

src/core/include/mp-units/ext/prime.h
test/static/prime_test.cpp

This is more involved than the Miller-Rabin test, but we can tame the complexity by breaking it down into helper functions, performing tasks such as:
- Find an appropriate D parameter.
- Increment the index of the (U_k, V_k) sequence elements by one.
- Double the index of the (U_k, V_k) sequence elements.
etc.
With these helpers, the algorithm becomes straightforward (see, for instance,
https://en.wikipedia.org/wiki/Lucas_pseudoprime#Strong_Lucas_pseudoprimes). We start by ruling out perfect squares (because if we don't, then the search for `D` will never terminate).  Then we find our `D`, and decompose `n + 1` into `s` and `d` parameters (exactly as we did for Miller-Rabin, except there we used `n - 1`).  At this point, the strong test is easy: check whether `U_d` is 0, then check `V_d` …

Add the Strong Lucas Probable Prime test

---

src/core/include/mp-units/ext/prime.h
src/core/include/mp-units/framework/magnitude.h
src/systems/include/mp-units/systems/hep.h
test/static/magnitude_test.cpp
test/static/prime_test.cpp

Baillie-PSW is technically a "probable prime" test.  However, it is known to be completely accurate on all 64-bit integers, and no known counterexample of any size has ever been found.  Thus, for our purposes, we can treat it as if it's deterministic, especially since we don't have any use cases for factoring numbers that don't fit in 64 bits, and we don't expect that we ever will.
See this description of the algorithm: <https://en.wikipedia.org/wiki/Baillie%E2%80%93PSW_primality_test#The_test>.  Note that all of the building blocks have already been added in prior PRs, so the implementation is now very easy.  We test this in the same way that we were testing the other prime checkers: easy cases, known pseudoprimes for Miller-Rabin and Strong Lucas, and very big primes.
With Baillie-PSW …

Use Baillie-PSW prime test to factor numbers

---

docs/api_reference/src/CMakeLists.txt
docs/api_reference/src/intro.tex
docs/api_reference/src/macros_extensions.tex
docs/api_reference/src/quantities.tex

This is still a WIP:
- [mp-units.pdf](https://github.com/user-attachments/files/18049450/mp-units.pdf)
- [mp-units-html.zip](https://github.com/user-attachments/files/18049451/mp-units-html.zip)
TBDs and still missing:

docs(ref): document most of `mp_units.core`

---

.github/generate-job-matrix.py

Since mp-units requires at least Xcode 15 we should have coverage on the latest compilers for operating system versions for macOS 13 (Ventura) and macOS 14 (Sequoia) as those are the operating systems with necessary compilers that our users would be using.
Now build with Xcode 15.2 instead of 15.0.1 which last version supported on macOS 13.
Add a build for Xcode 15.4 and Xcode 16.1 for testing macOS 14 builds. Since Xcode 16.1 is new most of our clients using macOS 14 would might more likely be using Xcode 15.4.
There might not be much C++ changes between Xcode 15.2 and Xcode 15.4 so perhaps we should drop 15.4 if adding three apple-clang builds is not worth the resources.

Update Xcode versions for apple-clang builds

---

.github/generate-job-matrix.py
conanfile.py
docs/getting_started/cpp_compiler_support.md
src/CMakeLists.txt

Specified the minimum apple-clang version to support `std::format` to 16 for _connanfile.py_.  Xcode 16 does include the `<format>` header but does not seem to have the __cpp_lib_format compatibility macro defined so a similar override was needed as we had for Clang 17.
To be able to use `std::format` with Xcode 16 I had to pass `-DMP_UNITS_API_STD_FORMAT=AUTO` when calling `cmake`.  Is this expected or is this a sign I missed something in my changes to _CMakeLists.txt_?

Enable use of std::format for AppleClang / Xcode 16

---

src/core/include/mp-units/framework/quantity_spec.h

Add a missing lint `bugprone-branch-clone` block closing for function `convertible_impl` in file `quantity_spec`. The following error is solved in consumer code:
```
[...]/mp-units-src/src/core/include/mp-units/framework/quantity_spec.h:1073:6:
error: unmatched 'NOLINTBEGIN' comment without a subsequent 'NOLINTEND' comment [clang-tidy-nolint]
1073 |   // NOLINTBEGIN(bugprone-branch-clone)
|      ^
```

fix: `quantity_spec` missing lint block end

---

test/static/concepts_test.cpp

This commit adds some static tests for the concept DimensionOf as requested in issue #497 .

Add static tests for concept DimensionOf

---

.github/generate-job-matrix.py
src/core/include/mp-units/framework/representation_concepts.h

The first attempted fix for long build times with Xcode 15 was causing a compiler crash.
The refactor to remove `concept Representation` seemed to cause an unexplained long build time for Xcode 15 building Kalman filter examples. Reverting the changes to `concept RepresentationOf` in Xcode 15 seems to resolve the long build times. I'm not sure if we should revert this change just for Xcode 15 or in general.

Fix Xcode long build times and/or crashes

---

src/core/include/mp-units/framework/quantity_point.h

fixes https://github.com/mpusz/mp-units/issues/707
Looked it over again and realized ref + point origin doesn't work but point origin + ref does so I just copied the working one's 'typename'.

fix/lvalue references + point origin does not compile

---

src/core/include/mp-units/ext/type_name.h

The function `type_name` is very compiler-dependent, its implementation already contains preprocessor branches for Clang, GCC and MSVC. In ReSharper (it's the [plugin for Visual Studio](https://www.jetbrains.com/resharper-cpp) and the language engine used in [CLion IDE](https://www.jetbrains.com/help/clion/clion-nova-introduction.html) and Rider) there is the special builtin `__rscpp_type_name` for getting type name. This builtin is more for efficient than extracting text from function signature on the one hand and avoids the need to exactly emulate macros `__PRETTY_FUNCTION__`/`__FUNCSIG__` in all compilers on the other hand.
The similar patch was [accepted](https://github.com/Neargye/magic_enum/pull/238) in another popular open-source C++ library …

Support ReSharper builtin for type name

---

src/core/include/mp-units/framework/quantity.h

It looks like every other method in `quantity` is constexpr (notably, this includes `numerical_value_in()` and its variants), so this seems like an oversight.

Make quantity conversion to Rep constexpr
