doc/INSTALL.md, src/include/units/bits/dim_consolidate.h, src/include/units/ratio.h, test/unit_test/static/math_test.cpp, test/unit_test/static/ratio_test.cpp
dealing with exponent during sqrt
fixes #58
=> dealing with exponent during sqrt

src/include/units/bits/unit_text.h
i thought it was my fork, but then the godlbolt version broke as well. 
not sure why/how
=> unit_text.h includes and 10^0

src/include/units/quantity_cast.h, src/include/units/ratio.h
better sqrt_impl
MUCH bigger range (although still not quite max -- see comments)
no recursion
make this example possible: https://godbolt.org/z/tDFkfR
=> Extend sqrt

README.md
fixes broken link to golbolt compiler in readme
=> fix link to godbolt compiler in readme

CMakeLists.txt, src/CMakeLists.txt
See https://cmake.org/cmake/help/latest/release/3.12.html#other, which adds `cxx_std_20`.
=> Fix minimum required CMake version

example/CMakeLists.txt, example/experimental_angle.cpp, example/linear_algebra.cpp, src/include/units/physical/dimensions.h, src/include/units/physical/si/angle.h, src/include/units/physical/si/torque.h
Experimental angle as dimension. Just for fun  since clearly it doesnt agree with the SI.
=> Kwikius angle

src/include/units/random.h, test/unit_test/runtime/CMakeLists.txt, test/unit_test/runtime/distribution_test.cpp
The last two, ```piecewise_constant_distribution``` and ```piecewise_linear_distribution```, were really messy, though.
Thanks!
=> Added STL random number distribution wrappers

example/foot_pound_second.cpp, src/include/units/physical/fps/force.h, src/include/units/physical/fps/length.h, src/include/units/physical/fps/mass.h, src/include/units/physical/fps/pressure.h
Added a bit more to the foot pound system & corrected one of the values in the example
=> Foot pound system

src/include/units/bits/common_quantity.h, src/include/units/concepts.h, src/include/units/quantity_cast.h, src/include/units/quantity_point.h, test/unit_test/static/CMakeLists.txt, test/unit_test/static/quantity_point_test.cpp
=> feat: quantity_point

src/include/units/physical/fps/length.h
Added a few more lengths. And the all important ' in 2'000, which is worth a pull request all by itself!
=> Some more fps lengths

src/include/units/physical/dimensions.h, src/include/units/physical/si.h, src/include/units/physical/si/angular_velocity.h, test/unit_test/static/si_test.cpp
Also a measure of progress when programming - how fast are you going round in circles with no observable side-effects.
=> Angular velocity for si system

src/include/units/quantity_point.h
=> refactor: nodiscard to functions

src/include/units/bits/external/type_traits.h, src/include/units/concepts.h
By the way, I'm using https://www.conventionalcommits.org in the commit messages.
=> refactor: simplify *_specialization_of

src/include/units/quantity.h
=> fix: parameter constness in constraints

src/include/units/quantity_cast.h, test/unit_test/static/quantity_test.cpp
=> fix: quantity_cast between different, equivalent dimensions

src/include/units/quantity.h, test/unit_test/static/quantity_test.cpp
=> fix: lack of compound assignment from dimensionless<one>

src/include/units/quantity.h, src/include/units/quantity_kind.h, test/unit_test/static/quantity_kind_test.cpp, test/unit_test/static/quantity_test.cpp, test/unit_test/static/unit_constants.cpp
=> fix: operators to behave like the underlying type's

docs/CHANGELOG.md, docs/reference/core/customization_points.rst, docs/use_cases/interoperability.rst, src/include/units/bits/basic_concepts.h, src/include/units/chrono.h, src/include/units/customization_points.h, src/include/units/quantity_point.h, src/include/units/quantity_point_kind.h, test/unit_test/static/chrono_test.cpp, test/unit_test/static/quantity_point_kind_test.cpp, test/unit_test/static/quantity_point_test.cpp
Resolves #172.
~~I still need to add tests for the quantity kinds.~~
=> feat: quantity point-like support

docs/CMakeLists.txt, docs/design/quantity_kind.rst, docs/framework/dimensions.rst, docs/framework/quantity_kinds.rst, example/glide_computer.cpp, src/include/units/quantity.h, src/include/units/quantity_kind.h, src/include/units/quantity_point_kind.h, test/unit_test/static/quantity_kind_test.cpp, test/unit_test/static/quantity_point_kind_test.cpp, test/unit_test/static/quantity_test.cpp
Use case rose up at https://github.com/mpusz/units/commit/8476517185bd49c2651b05b77a35c194242fd562#r47186626.
=> feat: full-on dimensional analysis between related quantity kinds

cmake/warnings.cmake, example/CMakeLists.txt, src/include/units/bits/external/downcasting.h, src/include/units/bits/external/fixed_string.h, src/include/units/bits/external/hacks.h, src/include/units/one_rep.h, src/include/units/quantity.h, src/include/units/quantity_cast.h, src/include/units/quantity_io.h, src/include/units/quantity_kind.h, src/include/units/quantity_point.h, src/include/units/quantity_point_kind.h, test/unit_test/static/custom_unit_test.cpp, test/unit_test/static/quantity_test.cpp, test/unit_test/static/si_cgs_test.cpp, test/unit_test/static/test_tools.h, test/unit_test/static/unit_constants.cpp
Resolves #209.
Also supports Clang 13 as well. Both requiring libstdc++.
=> feat: Clang 12 support

docs/CHANGELOG.md, src/core/include/units/bits/equivalent.h, test/unit_test/static/point_origin_test.cpp
=> fix: factor out _requires-expression_ and incomplete type for MSVC

src/core/include/units/math.h, test/unit_test/runtime/math_test.cpp, test/unit_test/static/chrono_test.cpp, test/unit_test/static/math_test.cpp
Relates to #307 
This is my first draft for the floor implemenation. For now, I added tests and implementation at the same place. Probaly you know best where to put them.
The implementations for ceil and round will follow once we are fine with the implementation for floor.
=> Feat: Floor

conanfile.py, src/core/CMakeLists.txt, src/core/include/units/bits/external/hacks.h, src/core/include/units/quantity.h, src/mp-unitsConfig.cmake, test/unit_test/static/quantity_test.cpp
=> refactor: update Clang 14 to not require range-v3

docs/framework/units.rst
CRTP must be recurring :smile:
=> docs: fix typo in units.rst

src/core/include/units/magnitude.h
This appears to cause problems under `-fno-exceptions` in some rare instances.
Should fix #390.
=> Replace compile-time exceptions with terminations

.github/workflows/ci-test-package-cmake.yml, .github/workflows/codeql-analysis.yml, .github/workflows/documentation.yml
These are the remaining 3 workflows missing from the last PR: https://github.com/mpusz/units/pull/415
=> Update missed workflows to use new Conan cache key

README.md
For background, see:
https://github.com/badges/shields/issues/8671
To verify that this works, see:
https://github.com/chiphogg/units/tree/chiphogg/badge
=> Fix badge image links

.github/workflows/ci-conan.yml, .github/workflows/ci-test-package-cmake.yml, .github/workflows/codeql.yml, README.md, conanfile.py, docs/getting_started/installation_and_usage.md, docs/getting_started/look_and_feel.md, docs/index.md, docs/users_guide/examples/hello_units.md, example/CMakeLists.txt, example/clcpp_response.cpp, example/conversion_factor.cpp, example/glide_computer.cpp, example/glide_computer_lib/glide_computer_lib.cpp, example/hello_units.cpp, example/include/geographic.h, example/include/ranged_representation.h, example/include/validated_type.h, example/si_constants.cpp, example/spectroscopy_units.cpp, example/unmanned_aerial_vehicle.cpp, src/CMakeLists.txt, src/core/include/mp-units/bits/external/hacks.h, src/core/include/mp-units/bits/fmt.h, src/core/include/mp-units/format.h, src/core/include/mp-units/ostream.h, src/core/include/mp-units/unit.h, test/runtime/fmt_test.cpp, test_package/conanfile.py
- units text output support
- quantity formatting grammar now suppors composition of the underlying formatters
- quantity format specification changes
Resolves #543
Resolves #503
=> feat!: New formatting grammar
